[default.extend-words]
# noice.nvim
noice = "noice"
# vim keymap
enew = "enew"
# key mapping in dot_config/nvim/lua/plugins/telescope-nvim.lua
fo = "fo"
# telescope-nvim
tabe = "tabe"
# dot_config/nvim/lua/plugins/configs/nvim-tree/actions.lua
nd = "nd"
# dot_config/nvim/lua/plugins/w3m-vim.lua
Extenal = "Extenal"

[files]
extend-exclude = [
  # NOTE: has many typos
  "dot_config/nvim/dotfyle.json",
  "CHANGELOG.md",
]
