[dev]
path = "~/ghq/github.com/mimikun/dev-plugins"

[rocks]

[plugins]
"rocks.nvim" = "2.40.4"
"rocks-git.nvim" = "2.5.0"
"rocks-lazy.nvim" = "1.1.1"
"rocks-edit.nvim" = "scm"
"rocks-treesitter.nvim" = "1.1.3"
"rocks-config.nvim" = "3.0.0"
"rocks-dev.nvim" = "1.7.0"

"plenary.nvim" = "scm"
nvim-web-devicons = "0.100"
"mini.icons" = "0.14.0"
"nui.nvim" = "0.3.0"
"toggleterm.nvim" = "2.12.0"
neorg = "9.1.1"

[plugins.nvim-treesitter-textobjects]
#version = "scm"
git = "RRethy/nvim-treesitter-textsubjects"

[plugins.nvim-nu]
git = "LhKipp/nvim-nu"

[plugins.nvim-ts-autotag]
#git = "windwp/nvim-ts-autotag"
version = "scm"

[plugins."nvim-ts-context-commentstring"]
git = "JoosepAlviste/nvim-ts-context-commentstring"
#version = "scm"

[plugins."vim-toml"]
git = "cespare/vim-toml"

[plugins."vim-duckscript"]
git = "nastevens/vim-duckscript"

#---------------------------------------------

[plugins."2048.nvim"]
#git = "NStefan002/2048.nvim"
version = "2.8.2"
cmd = "Play2048"

[plugins."accelerated-jk.nvim"]
git = "rainbowhxch/accelerated-jk.nvim"
event = "BufRead"

[plugins.alpha-nvim]
#git = "goolord/alpha-nvim"
version = "scm"
cmd = "Alpha"
event = "VimEnter"

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"
event = "BufEnter"
cmd = [
  "BufferPrevious",
  "BufferNext",
  "BufferMovePrevious",
  "BufferMoveNext",
  "BufferGoto",
  "BufferLast",
  "BufferPin",
  "BufferClose",
  "BufferRestore",
  "BufferWipeout",
  "BufferCloseAllButCurrent",
  "BufferCloseAllButVisible",
  "BufferCloseAllButPinned",
  "BufferCloseAllButCurrentOrPinned",
  "BufferCloseBuffersLeft",
  "BufferCloseBuffersRight",
  "BufferPick",
  "BufferPickDelete",
  "BufferOrderByBufferNumber",
  "BufferOrderByName",
  "BufferOrderByDirectory",
  "BufferOrderByLanguage",
  "BufferOrderByWindowNumber",
  "BarbarEnable",
  "BarbarDisable",
]

[plugins."buffer-reopen.nvim"]
git = "iamyoki/buffer-reopen.nvim"
cmd = "BufferHistory"

[plugins."ccc.nvim"]
git = "uga-rosa/ccc.nvim"
#version = "1.6.0"
cmd = [
  "CccPick",
  "CccConvert",
  "CccHighlighterEnable",
  "CccHighlighterDisable",
  "CccHighlighterToggle",
]
event = "BufEnter"

[plugins."comment.nvim"]
#git = "numToStr/Comment.nvim"
version = "0.8.0"

[plugins."context-menu.nvim"]
git = "LintaoAmons/context-menu.nvim"
cmd = "ContextMenu"

#[plugins."copilot.lua"]
#version = "scm"

[plugins."crates.nvim"]
git = "saecki/crates.nvim"
cmd = "Crates"
event = "BufRead Cargo.toml"

[plugins."dial.nvim"]
git = "monaqa/dial.nvim"
cmd = [
  "DialIncrement",
  "DialDecrement",
]
#event = "VeryLazy"

[plugins."diffview.nvim"]
#git = "sindrets/diffview.nvim",
version = "scm"
cmd = [
  "DiffviewOpen",
  "DiffviewFileHistory",
  "DiffviewClose",
  "DiffviewToggleFiles",
  "DiffviewFocusFiles",
  "DiffviewRefresh",
  "DiffviewLog",
]

[plugins."dotfyle-metadata.nvim"]
git = "creativenull/dotfyle-metadata.nvim"
cmd = [
  "DotfyleGenerate",
  "DotfyleOpen",
]
config = true

[plugins."dressing.nvim"]
#git = "stevearc/dressing.nvim"
version = "3.0.0"

[plugins."fidget.nvim"]
#git = "j-hui/fidget.nvim"
version = "1.4.1"
cmd = "Fidget"

[plugins."flagmode.nvim"]
git = "prichrd/flagmode.nvim"
cmd = [
  "FlagToggle",
  "FlagActivate",
  "FlagDeactivate",
]

[plugins."garbage-day.nvim"]
git = "zeioth/garbage-day.nvim"
#event = "VeryLazy"
config = true
opt = true

[plugins."gitgraph.nvim"]
git = "isakbm/gitgraph.nvim"
cmd = "GitGraph"
keys = { lhs = "<leader>gl", rhs = 'lua require("gitgraph").draw({}, { all = true, max_count = 5000 }', mode = "n", desc = "GitGraph - Draw"}

[plugins."gitsigns.nvim"]
#git = "lewis6991/gitsigns.nvim"
version = "0.9.0"
event = "VimEnter"

[plugins."glow.nvim"]
version = "0.2.0"
cmd = "Glow"

[plugins."grapple.nvim"]
#git = "cbochs/grapple.nvim"
version = "0.30.0"
cmd = "Grapple"
event = ["BufReadPost", "BufNewFile"]

[plugins."hardtime.nvim"]
#git = "m4xshen/hardtime.nvim",
version = "scm"
cmd = "Hardtime"

[plugins."haunt.nvim"]
git = "adigitoleo/haunt.nvim"
# NOTE: official repository
# "https://git.sr.ht/~adigitoleo/haunt.nvim"
cmd = [
  "HauntTerm",
  "HauntHelp",
  "HauntMan",
  "HauntLs",
  "HauntReset",
]

[plugins."hawtkeys.nvim"]
git = "tris203/hawtkeys.nvim"
cmd = [
  "Hawtkeys",
  "HawtkeysAll",
  "HawtkeysDupes",
]

[plugins."helpview.nvim"]
#git = "OXY2DEV/helpview.nvim"
version = "1.1.0"
ft = "help"
cmd = "Helpview"

[plugins."hover.nvim"]
#git = "lewis6991/hover.nvim"
version = "scm"
#event = "VeryLazy"

[plugins."human-rights.nvim"]
git = "mimikun/human-rights.nvim"
#dev = true
cmd = [
  "ShowCpu",
  "ShowMemory",
  "ShowParallelism",
  "ShowDisk",
]

[plugins."indent-blankline.nvim"]
git = "lukas-reineke/indent-blankline.nvim"
#version = "3.8.2"
cmd = [
  "IBLEnable",
  "IBLDisable",
  "IBLToggle",
  "IBLEnableScope",
  "IBLDisableScope",
  "IBLToggleScope",
]
event = "BufEnter"

[plugins."keyseer.nvim"]
git = "jokajak/keyseer.nvim"
cmd = "KeySeer"

[plugins."lazydocker.nvim"]
git = "mgierada/lazydocker.nvim"
cmd = "Lazydocker"
event = "BufRead"
config = true

[plugins."lazygit.nvim"]
#git = "kdheepak/lazygit.nvim"
version = "scm"
cmds = [
  "LazyGit",
  "LazyGitConfig",
  "LazyGitCurrentFile",
  "LazyGitFilter",
  "LazyGitFilterCurrentFile",
]
keys = { lhs = "<leader>lg", rhs = "<cmd>LazyGit<cr>", desc = "LazyGit" }

[plugins."lazysql.nvim"]
git = "LostbBlizzard/lazysql.nvim"
cmd = "LazySql"
config = true

[plugins."legendary.nvim"]
#git = "mrjones2014/legendary.nvim"
version = "2.13.11"
cmd = [
  "Legendary",
  "LegendaryRepeat",
]


[plugins."lspsaga.nvim"]
#git = "nvimdev/lspsaga.nvim"
version = "scm"
cmd = "Lspsaga"
event = "LspAttach"

[plugins."lualine.nvim"]
#git = "nvim-lualine/lualine.nvim"
version = "scm"
event = "BufEnter"

[plugins."luminate.nvim"]
git = "mei28/luminate.nvim"
#event = "VeryLazy"
config = true

[plugins.luasnip]
version = "2.3.0"

[plugins."markdown-toggle.nvim"]
git = "roodolv/markdown-toggle.nvim"
ft = ["markdown", "markdown.mdx"]

[plugins."markview.nvim"]
git = "OXY2DEV/markview.nvim"
version = "24.0.0"
cmd = "Markview"
event = "BufEnter"

[plugins."mason.nvim"]
version = "1.10.0"

[plugins."mkdir.nvim"]
git = "jghauser/mkdir.nvim"
keys = { lhs = "w", mode = "c", desc = "You can mkdir -p" }
config = true

[plugins."moody.nvim"]
git = "svampkorg/moody.nvim"
event = ["ModeChanged", "BufWinEnter", "WinEnter"]

[plugins.neogit]
#git = "NeogitOrg/neogit"
version = "1.0.0"
cmd = "Neogit"

[plugins."neominimap.nvim"]
git = "Isrothy/neominimap.nvim"
cmd = "Neominimap"

[plugins."no-neck-pain.nvim"]
#git = "shortcuts/no-neck-pain.nvim"
version = "2.0.6"
cmd = [
  "NoNeckPain",
  "NoNeckPainResize",
  "NoNeckPainToggleLeftSide",
  "NoNeckPainToggleRightSide",
  "NoNeckPainWidthUp",
  "NoNeckPainWidthDown",
]

[plugins."noice.nvim"]
#git = "folke/noice.nvim"
version = "4.5.2"
cmd = [
  "Noice",
  "NoiceLast",
  "NoiceDisable",
]
#event = "VeryLazy"

# TODO:

[plugins."num-utils.nvim"]
git = "mimikun/num-utils.nvim"
cmd = [
  "NumToHex",
  "NumToBinary",
  "NumToOctal",
  "NumToDecimal",
]

[plugins.nvim-autopairs]
version = "scm"
event = "InsertEnter"

[plugins.nvim-bqf]
#git = "kevinhwang91/nvim-bqf"
version = "1.1.1"
ft = "qf"
cmd = [
  "BqfEnable",
  "BqfDisable",
  "BqfToggle",
  "BqfAutoToggle",
]

[plugins.nvim-cursorline]
#git = "yamatsum/nvim-cursorline"
version = "scm"

[plugins.nvim-dap-ui]
version = "4.0.0"

[plugins.nvim-lspconfig]
version = "1.0.0"

[plugins."nvim-navbuddy"]
git = "SmiteshP/nvim-navbuddy"
cmd = "Navbuddy"

[plugins.nvim-navic]
#git = "SmiteshP/nvim-navic"
version = "scm"
opt = true

[plugins.nvim-notify]
#git = "rcarriga/nvim-notify"
version = "3.14.0"

[plugins.nvim-surround]
version = "2.1.5"

[plugins."nvim-tree.lua"]
version = "1.6.0"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
#version = "scm"
build = ":TSUpdate"
#event = "VeryLazy"

[plugins."obsidian.nvim"]
version = "3.9.0"

[plugins."octo.nvim"]
#"pwntester/octo.nvim"
version = "scm"
cmd = "Octo"

[plugins."oil-git-status.nvim"]
git = "refractalize/oil-git-status.nvim"
ft = "oil"
config = true

[plugins."oil.nvim"]
#git = "stevearc/oil.nvim"
version = "2.12.2"
cmd = "Oil"

[plugins."overseer.nvim"]
#"stevearc/overseer.nvim"
version = "1.4.0"
cmd = [
  "OverseerOpen",
  "OverseerClose",
  "OverseerToggle",
  "OverseerSaveBundle",
  "OverseerLoadBundle",
  "OverseerDeleteBundle",
  "OverseerRunCmd",
  "OverseerRun",
  "OverseerInfo",
  "OverseerBuild",
  "OverseerQuickAction",
  "OverseerTaskAction",
  "OverseerClearCache",
]
config = true

[plugins."package-info.nvim"]
#git = "vuki656/package-info.nvim"
event = "BufRead package.json"
version = "2.0"

[plugins."render-markdown.nvim"]
#git = "MeanderingProgrammer/render-markdown.nvim"
version = "7.4.0"
ft = ["markdown", "vimwiki"]
cmd = "RenderMarkdown"
event = "BufEnter"

[plugins.rustaceanvim]
#git = "mrcjkb/rustaceanvim"
version = "5.13.0"
cmds = [
  "RustAnalyzer",
  "Rustc",
  "RustLsp",
]
config = true

[plugins."satellite.nvim"]
git = "lewis6991/satellite.nvim"
cmd = [
  "SatelliteEnable",
  "SatelliteDisable",
  "SatelliteRefresh",
]
event = "VimEnter"

[plugins."screenkey.nvim"]
#git = "NStefan002/screenkey.nvim"
version = "2.2.1"
cmd = "Screenkey"

[plugins."sidebar.nvim"]
git = "sidebar-nvim/sidebar.nvim"
cmd = [
    "SidebarNvimToggle",
    "SidebarNvimClose",
    "SidebarNvimOpen",
    "SidebarNvimUpdate",
    "SidebarNvimResize",
    "SidebarNvimFocus",
]
event = "BufEnter"

[plugins."smart-open.nvim"]
#git = "danielfalk/smart-open.nvim"
version = "scm"

[plugins."smoothcursor.nvim"]
#git = "gen740/SmoothCursor.nvim"
version = "scm"
cmd = [
  "SmoothCursorStart",
  "SmoothCursorStop",
  "SmoothCursorStatus",
  "SmoothCursorToggle",
  "SmoothCursorFancyToggle",
  "SmoothCursorFancyOn",
  "SmoothCursorFancyOff",
  "SmoothCursorDeleteSigns",
  "SmoothCursorJump",
]
event = "BufEnter"

[plugins."sqlite.lua"]
#git = "kkharji/sqlite.lua"
version = "1.2.2"

[plugins."telescope.nvim"]
#git = "nvim-telescope/telescope.nvim"
version = "scm"
cmd = "Telescope"

[plugins."telescope-fzf-native.nvim"]
git = "nvim-telescope/telescope-fzf-native.nvim"
build = "make"

[plugins."todo-comments.nvim"]
#git = "folke/todo-comments.nvim"
version = "1.4.0"
cmd = [
  "TodoQuickFix",
  "TodoLocList",
  "TodoTelescope",
]
event = "BufEnter"

[plugins."toggle.nvim"]
git = "gregorias/toggle.nvim"
#version = "2.0"
#event = "VeryLazy"

[plugins."template.nvim"]
git = "nvimdev/template.nvim"
cmd = "Template"

[plugins."translate.nvim"]
git = "uga-rosa/translate.nvim"
cmd = "TranslateJa"

[plugins."transparent.nvim"]
git = "xiyaowong/transparent.nvim"
cmd = [
  "TransparentEnable",
  "TransparentDisable",
  "TransparentToggle",
]

[plugins.treesj]
#git = "Wansmer/treesj"
version = "scm"
cmd = [
  "TSJToggle",
  "TSJSplit",
  "TSJoin",
]
opt = true

[plugins."trouble.nvim"]
#git = "folke/trouble.nvim"
version = "3.6.0"
cmd = "Trouble"

[plugins."typos.nvim"]
git = "poljar/typos.nvim"

[plugins."vim-illuminate"]
git = "RRethy/vim-illuminate"
cmd = [
  "IlluminatePause",
  "IlluminateResume",
  "IlluminateToggle",
  "IlluminatePauseBuf",
  "IlluminateResumeBuf",
  "IlluminateToggleBuf",
]

[plugins."wezterm.nvim"]
git = "willothy/wezterm.nvim"
dev = false
cmd = "WeztermSpawn"

[plugins."which-key.nvim"]
#git = "folke/which-key.nvim"
version = "3.13.3"
cmd = "WhichKey"
#event = "VeryLazy"
keys = { lhs = "<leader>?", rhs = 'lua require("which-key").show({ global = false })', desc = "Buffer Local Keymaps (which-key)" }

[plugins."zen-mode.nvim"]
#git = "folke/zen-mode.nvim"
version = "1.4.0"
cmd = "ZenMode"

#--------------------------------------------------------------------

# denops plugins
[plugins."denops.vim"]
git = "vim-denops/denops.vim"

[plugins."dps-translate-vim"]
git = "Omochice/dps-translate-vim"
cmd = [
  "Translate",
  "TranslateJoin",
]

[plugins."silhouette.nvim"]
git = "tadashi-aikawa/silhouette.nvim"
ft = "markdown"
cmd = [
  "SilhouetteInsertTasks",
  "SilhouetteMoveToProgress",
  "SilhouetteShowTaskDates",
]

[plugins.skkeleton]
git = "vim-skk/skkeleton"

# Vim Script plugins
[plugins."calendar-vim"]
git= "mattn/calendar-vim"
cmd = "Calendar"

[plugins."chezmoi.vim"]
git = "alker0/chezmoi.vim"

[plugins."eskk.vim"]
git = "vim-skk/eskk.vim"
cmd = [
    "EskkMap",
    "EskkUnmap",
    "EskkForgetRegisteredWords",
    "EskkUpdateDictionary",
    "EskkFixDictionary",
    "EskkReload",
    "EskkEnable",
    "EskkDisable",
    "EskkToggle",
]

[plugins."migemo-search.vim"]
git = "rhysd/migemo-search.vim"
opt = true

[plugins."vim-ambiwidth"]
git = "rbtnn/vim-ambiwidth"

[plugins."vim-cargo-make"]
git = "nastevens/vim-cargo-make"
ft = "cargo-make"

[plugins."vim-kitty"]
git = "fladson/vim-kitty"
ft = "kitty"

[plugins."vim-quickrun"]
git = "thinca/vim-quickrun"
cmd = "QuickRun"

[plugins."vim-teraterm"]
git = "k-takata/vim-teraterm"
ft = "ttl"

[plugins."vimdoc-ja"]
git = "vim-jp/vimdoc-ja"
keys = { lhs = "h", mode = "c", desc = "open [H]elp" }

#-------------------------------------------------------------------------

