[dev]
path = "~/ghq/github.com/mimikun/dev-plugins"

[rocks]

[plugins]
"rocks.nvim" = "2.40.4"
"rocks-git.nvim" = "2.5.0"
"rocks-lazy.nvim" = "1.1.1"
"rocks-edit.nvim" = "scm"
"rocks-treesitter.nvim" = "1.1.3"
"rocks-config.nvim" = "3.0.0"
"rocks-dev.nvim" = "1.7.0"
"2048.nvim" = "2.8.2"
alpha-nvim = "scm"
"ccc.nvim" = "1.6.0"
"comment.nvim" = "0.8.0"
"copilot.lua" = "scm"
"diffview.nvim" = "scm"
"dressing.nvim" = "3.0.0"
"fidget.nvim" = "1.4.1"
"gitsigns.nvim" = "0.9.0"
"glow.nvim" = "0.2.0"
"grapple.nvim" = "0.30.0"
"hardtime.nvim" = "scm"
"helpview.nvim" = "1.1.0"
"hover.nvim" = "scm"
"indent-blankline.nvim" = "3.8.2"
"lazydev.nvim" = "1.8.0"
"lazygit.nvim" = "scm"
"legendary.nvim" = "2.13.11"
"lspsaga.nvim" = "scm"
luasnip = "2.3.0"
"lualine.nvim" = "scm"
"markview.nvim" = "24.0.0"
"mason.nvim" = "1.10.0"
neogit = "1.0.0"
"no-neck-pain.nvim" = "2.0.6"
"noice.nvim" = "4.5.2"
"none-ls.nvim" = "scm"
nvim-autopairs = "scm"
nvim-bqf = "1.1.1"
nvim-cursorline = "scm"
nvim-dap-ui = "4.0.0"
nvim-lspconfig = "1.0.0"
nvim-navic = "scm"
nvim-notify = "3.14.0"
nvim-surround = "2.1.5"
"nvim-tree.lua" = "1.6.0"
"obsidian.nvim" = "3.9.0"
"octo.nvim" = "scm"
"oil.nvim" = "2.12.2"
"overseer.nvim" = "1.4.0"
"package-info.nvim" = "2.0"
"render-markdown.nvim" = "7.4.0"
rustaceanvim = "5.13.0"
"screenkey.nvim" = "2.2.1"
"smart-open.nvim" = "scm"
"smoothcursor.nvim" = "scm"
"sqlite.lua" = "1.2.2"
"telescope.nvim" = "scm"
"todo-comments.nvim" = "1.4.0"
treesj = "scm"
"trouble.nvim" = "3.6.0"
"which-key.nvim" = "3.13.3"
"zen-mode.nvim" = "1.4.0"

[plugins."denops.vim"]
git = "vim-denops/denops.vim"

[plugins.skkeleton]
git = "vim-skk/skkeleton"

[plugins."vim-fall"]
git = "lambdalisue/vim-fall"

[plugins."dial.nvim"]
git = "monaqa/dial.nvim"

#[plugins."rocks-spec-template.nvim"]
# NOTE: rocks.nvim RockSpec
#---@type string The rock version
#version = ""
#---@type boolean Set to `true` to prevent rocks from being loaded eagerly
#opt = true
#---@type boolean Pinned rocks will not be updated
#pin = false
# NOTE: rocks-git.nvim additional RockSpec
#---@type string Name of the plugin.
#name = "rockspec-template"
#---@type string Git short name, e.g. 'nvim-neorocks/rocks-git.nvim', or a git URL.
#git = "mimikun/rocks-spec-template.nvim"
# WARN: duplicate rocks.nvim RockSpec's opt parameter
#---@type boolean If 'true', will not be loaded on startup. Can be loaded manually with `:packadd!`.
#opt = true
#---@type string Git revision or tag to checkout.
#rev = ""
#---@type string Git branch to checkout.
#branch = ""
#---@type string Shell or Vimscript command to run after install/update. Will run a vim command if prefixed with ':'.
#build = ""
#---@type boolean Ignore tags when updating and prioritise git revisions. default `false`
#ignore_tags = false
# NOTE: rocks-config.nvim additional RockSpec
#---@type string Will execute `.config/nvim/lua/plugins/statusline.lua`
#config = "plugins.statusline"
# NOTE: rocks-dev.nvim additional RockSpec
#---@type string local plugin directory
#dir = "/path/to/mimikun/rocksspec-template.nvim"
#---@type boolean If set dev.path, and `dev = true`, can loading local plugins.
#dev = false
# NOTE: rocks-lazy.nvim additional RockSpec
#---@type string? | string[] Lazy-load on an event (`:h autocmd-events`).
#event = "BufEnter"
#---@type string? | string[] Lazy-load on a command (`:h user-commands`).
#cmd = "Cmdname"
#---@type string? | string[] Lazy-load on a `:h filetype` event.
#ft = "lua"
#---@type string? | string[] | rocks.lazy.KeysSpec[] Lazy-load on key mappings.
#keys = [{ lhs = "<leader>ft", rhs = "<CMD>Neotree toggle<CR>", desc = "NeoTree toggle" },]
#---@type string? | string[] Lazy-load when setting a colorscheme.
#colorscheme = [
#    "kanagawa",
#    "kanagawa-dragon",
#    "kanagawa-lotus",
#    "kanagawa-wave"
#]
# NOTE: rocks.lazy.KeysSpec
#- `rocks.lazy.KeysSpec`: table
#    - `lhs`: `string`
#    - `rhs`: `string?`
#    - `mode`: `string?` or `string[]` (default: `"n"`)
#    - `[string]`: Options, see `:h vim.keymap.set`
